# Generated by Django 3.2.7 on 2021-09-10 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('photo', models.ImageField(upload_to='vendor/')),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=12)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
