# Generated by Django 3.2.7 on 2021-09-10 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0007_auto_20210910_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='purchase',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='Management.purchase'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='purchase_quantity',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='sale',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='Management.sale'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='sale_quantity',
            field=models.FloatField(default=0, null=True),
        ),
    ]
