# Generated by Django 3.2.7 on 2021-09-10 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0010_auto_20210910_2335'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_phn', models.CharField(max_length=12)),
            ],
        ),
        migrations.RemoveField(
            model_name='sale',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='customer_phn',
        ),
        migrations.AddField(
            model_name='sale',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Management.customer'),
            preserve_default=False,
        ),
    ]
